//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class abbonementen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abbonementen()
        {
            this.abbonementen_kwaliteiten = new HashSet<abbonementen_kwaliteiten>();
            this.gebruikers_abbonementen = new HashSet<gebruikers_abbonementen>();
        }
    
        public int abbonement_id { get; set; }
        public string naam { get; set; }
        public int prijs_in_centen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abbonementen_kwaliteiten> abbonementen_kwaliteiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gebruikers_abbonementen> gebruikers_abbonementen { get; set; }
    }
}
