//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class afleveringen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public afleveringen()
        {
            this.afleveringen_kwaliteiten = new HashSet<afleveringen_kwaliteiten>();
            this.afleveringen_ondertitelingen = new HashSet<afleveringen_ondertitelingen>();
            this.afleveringen1 = new HashSet<afleveringen>();
            this.kijk_histories = new HashSet<kijk_histories>();
        }
    
        public int aflevering_id { get; set; }
        public int seizoen_id { get; set; }
        public Nullable<int> volgende_aflevering_id { get; set; }
        public string naam { get; set; }
        public int tijdsduur_in_seconden { get; set; }
        public int aftiteling_tijdstip_in_seconden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afleveringen_kwaliteiten> afleveringen_kwaliteiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afleveringen_ondertitelingen> afleveringen_ondertitelingen { get; set; }
        public virtual seizoenen seizoenen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afleveringen> afleveringen1 { get; set; }
        public virtual afleveringen afleveringen2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kijk_histories> kijk_histories { get; set; }
    }
}
