//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class gebruikers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gebruikers()
        {
            this.gebruikers_abbonementen = new HashSet<gebruikers_abbonementen>();
            this.profielen = new HashSet<profielen>();
        }
    
        public int gebruiker_id { get; set; }
        public string emailadres { get; set; }
        public string wachtwoord { get; set; }
        public bool actief { get; set; }
        public bool geblokkeerd { get; set; }
        public System.DateTime geblokkeerd_tot { get; set; }
        public short foutieve_inlogpogingen { get; set; }
        public string reset_token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gebruikers_abbonementen> gebruikers_abbonementen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profielen> profielen { get; set; }
    }
}
