//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class kijk_histories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kijk_histories()
        {
            this.films = new HashSet<films>();
            this.afleveringen = new HashSet<afleveringen>();
        }
    
        public int kijk_historie_id { get; set; }
        public int profiel_id { get; set; }
        public int tijdstip_in_seconden { get; set; }
        public Nullable<System.DateTime> gekeken_op { get; set; }
    
        public virtual profielen profielen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<films> films { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afleveringen> afleveringen { get; set; }
    }
}
