//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netflixEntities : DbContext
    {
        public netflixEntities()
            : base("name=netflixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abbonementen> abbonementen { get; set; }
        public virtual DbSet<afleveringen> afleveringen { get; set; }
        public virtual DbSet<films> films { get; set; }
        public virtual DbSet<gebruikers> gebruikers { get; set; }
        public virtual DbSet<genres_voorkeuren> genres_voorkeuren { get; set; }
        public virtual DbSet<kijk_histories> kijk_histories { get; set; }
        public virtual DbSet<kijklijst_items> kijklijst_items { get; set; }
        public virtual DbSet<profielen> profielen { get; set; }
        public virtual DbSet<seizoenen> seizoenen { get; set; }
        public virtual DbSet<series> series { get; set; }
        public virtual DbSet<voorkeuren> voorkeuren { get; set; }
        public virtual DbSet<abbonementen_kwaliteiten> abbonementen_kwaliteiten { get; set; }
        public virtual DbSet<afleveringen_kwaliteiten> afleveringen_kwaliteiten { get; set; }
        public virtual DbSet<afleveringen_ondertitelingen> afleveringen_ondertitelingen { get; set; }
        public virtual DbSet<films_genres> films_genres { get; set; }
        public virtual DbSet<films_kijkwijzer_indicaties> films_kijkwijzer_indicaties { get; set; }
        public virtual DbSet<films_kwaliteiten> films_kwaliteiten { get; set; }
        public virtual DbSet<films_ondertitelingen> films_ondertitelingen { get; set; }
        public virtual DbSet<gebruikers_abbonementen> gebruikers_abbonementen { get; set; }
        public virtual DbSet<series_genres> series_genres { get; set; }
        public virtual DbSet<series_kijkwijzer_indicaties> series_kijkwijzer_indicaties { get; set; }
        public virtual DbSet<voorkeuren_kijkwijzer_indicaties> voorkeuren_kijkwijzer_indicaties { get; set; }
    }
}
