//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class profielen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profielen()
        {
            this.kijk_histories = new HashSet<kijk_histories>();
            this.kijklijst_items = new HashSet<kijklijst_items>();
            this.voorkeuren = new HashSet<voorkeuren>();
        }
    
        public int profiel_id { get; set; }
        public int gebruiker_id { get; set; }
        public string naam { get; set; }
        public string profiel_foto_locatie { get; set; }
        public System.DateTime geboorte_datum { get; set; }
        public string taal { get; set; }
        public bool ondertiteling { get; set; }
    
        public virtual gebruikers gebruikers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kijk_histories> kijk_histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kijklijst_items> kijklijst_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voorkeuren> voorkeuren { get; set; }
    }
}
