//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases2
{
    using System;
    using System.Collections.Generic;
    
    public partial class voorkeuren
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voorkeuren()
        {
            this.genres_voorkeuren = new HashSet<genres_voorkeuren>();
            this.voorkeuren_kijkwijzer_indicaties = new HashSet<voorkeuren_kijkwijzer_indicaties>();
        }
    
        public int voorkeur_id { get; set; }
        public int profiel_id { get; set; }
        public bool film_interesse { get; set; }
        public bool serie_interesse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genres_voorkeuren> genres_voorkeuren { get; set; }
        public virtual profielen profielen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voorkeuren_kijkwijzer_indicaties> voorkeuren_kijkwijzer_indicaties { get; set; }
    }
}
